bootstrap:
  servers: pkc-p11xm.us-east-1.aws.confluent.cloud:9092

security:
  protocol: SASL_SSL

sasl:
  jaas:
    config: org.apache.common.security.plain.PLainLoginModule required username=<CLUSTER API KEY> password=<CLUSTER SECRET>;
  mechanism: PLAIN

client:
  dns:
    lookup: use_all_dns_ips

session:
  timeout:
    ms: 45000

acks: all

key:
  serializer: org.apache.kafka.common.serialization.StringSerializer
  deserializer: org.apache.kafka.common.serialization.StringDeserializer

value:
  serializer: org.apache.kafka.common.serialization.StringSerializer
  deserializer: org.apache.kafka.common.serialization.StringDeserializer

